service: epsagon-deploy
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-epsagon
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, env:AWS_REGION, env:AWS_DEFAULT_REGION}
  stage: ${opt:stage, 'development'}
  stackTags:
    Business: "green"
    Environment: ${self:custom.environment}
    Product: "epsagon-deploy-demo"
    Team: "tools-cc"
  versionFunctions: false
  logs:
    restApi: true
  logRetentionInDays: 90
  tracing:
    apiGateway: true
    lambda: true

custom:
  environment: ${opt:environment, 'development'}
  epsagon:
    token: ${opt:epsagonToken}
    disable: false
    appName: ${self:service}-${self:provider.stage}
    metadataOnly: false
  webpack:
    webpackConfig: 'webpack.config.ts'
    packager: 'yarn'

functions:
  hello0:
    handler: handler.hello
    epsagon:
      disable: true
    events:
      - http:
          method: get
          path: hello0
  hello1:
    handler: handler.hello
    epsagon:
      disable: true
    events:
      - http:
          method: get
          path: hello1
  hello2:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello2
  hello3:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello3
  hello4:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello4
  hello5:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello5
  hello6:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello6
  hello7:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello7
  hello8:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello8
  hello9:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello9
  hello10:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello10
  hello11:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello11
  hello12:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello12
  hello13:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello13
  hello14:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello14
  hello15:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello15
  hello16:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello16
  getTemplateAdfHandler:
    handler: handler.getTemplateAdf
    events:
      - http:
          method: get
          path: template
